-- Family World Cup 2026 — Supabase schema + seed (generated by scripts/gen-schema.mjs)
-- HOW TO USE: open your Supabase project → SQL Editor → paste this whole file → Run.
-- Safe to re-run: it creates tables only if missing and upserts the fixtures.

-- ---------- tables ----------
create table if not exists players (
  id         bigint generated always as identity primary key,
  name       text not null,
  sort_order int  not null default 0
);

create table if not exists matches (
  match_no    int  primary key,
  stage       text not null,            -- group | R32 | R16 | QF | SF | 3rd | Final
  group_label text,                     -- A..L for the group stage, null otherwise
  home_team   text not null,
  away_team   text not null,
  kickoff     timestamptz not null,     -- stored in UTC, shown in each viewer's local time
  home_score  int,                      -- null until the match is played / synced
  away_score  int
);

create table if not exists predictions (
  id         bigint generated always as identity primary key,
  match_no   int    not null references matches(match_no) on delete cascade,
  player_id  bigint not null references players(id) on delete cascade,
  pred_home  int    not null check (pred_home >= 0 and pred_home <= 99),
  pred_away  int    not null check (pred_away >= 0 and pred_away <= 99),
  updated_at timestamptz not null default now(),
  unique (match_no, player_id)
);

-- ---------- row level security (trust-based, no login) ----------
alter table players     enable row level security;
alter table matches     enable row level security;
alter table predictions enable row level security;

drop policy if exists "read players"        on players;
drop policy if exists "rename players"       on players;
drop policy if exists "add players"          on players;
drop policy if exists "remove players"       on players;
drop policy if exists "read matches"         on matches;
drop policy if exists "read predictions"     on predictions;
drop policy if exists "insert predictions"   on predictions;
drop policy if exists "update predictions"   on predictions;

-- everyone can read everything
create policy "read players"     on players     for select using (true);
create policy "read matches"     on matches     for select using (true);
create policy "read predictions" on predictions for select using (true);

-- anyone can rename / add / remove players (Settings screen) — trust-based
create policy "rename players" on players for update using (true) with check (true);
create policy "add players"    on players for insert with check (true);
create policy "remove players" on players for delete using (true);

-- predictions can be written/edited only BEFORE kickoff (authoritative lock)
create policy "insert predictions" on predictions for insert
  with check (exists (
    select 1 from matches m where m.match_no = predictions.match_no and now() < m.kickoff
  ));
create policy "update predictions" on predictions for update
  using (exists (
    select 1 from matches m where m.match_no = predictions.match_no and now() < m.kickoff
  ))
  with check (exists (
    select 1 from matches m where m.match_no = predictions.match_no and now() < m.kickoff
  ));
-- NOTE: 'matches' has no anon write policy, so scores/fixtures can only be changed
-- by the daily sync function, which uses the service-role key and bypasses RLS.

-- ---------- seed: 5 players (only if the table is empty) ----------
insert into players (name, sort_order)
select v.name, v.sort_order
from (values
  ('Player 1', 1), ('Player 2', 2), ('Player 3', 3), ('Player 4', 4), ('Player 5', 5)
) as v(name, sort_order)
where not exists (select 1 from players);

-- ---------- seed: 104 fixtures ----------
insert into matches (match_no, stage, group_label, home_team, away_team, kickoff, home_score, away_score) values
  (1, 'group', 'A', 'Mexico', 'South Africa', '2026-06-11T19:00:00.000Z', 2, 0),
  (2, 'group', 'A', 'South Korea', 'Czech Republic', '2026-06-12T02:00:00.000Z', 2, 1),
  (3, 'group', 'A', 'Czech Republic', 'South Africa', '2026-06-18T16:00:00.000Z', null, null),
  (4, 'group', 'A', 'Mexico', 'South Korea', '2026-06-19T01:00:00.000Z', null, null),
  (5, 'group', 'A', 'Czech Republic', 'Mexico', '2026-06-25T01:00:00.000Z', null, null),
  (6, 'group', 'A', 'South Africa', 'South Korea', '2026-06-25T01:00:00.000Z', null, null),
  (7, 'group', 'B', 'Canada', 'Bosnia & Herzegovina', '2026-06-12T19:00:00.000Z', null, null),
  (8, 'group', 'B', 'Qatar', 'Switzerland', '2026-06-13T19:00:00.000Z', null, null),
  (9, 'group', 'B', 'Switzerland', 'Bosnia & Herzegovina', '2026-06-18T19:00:00.000Z', null, null),
  (10, 'group', 'B', 'Canada', 'Qatar', '2026-06-18T22:00:00.000Z', null, null),
  (11, 'group', 'B', 'Switzerland', 'Canada', '2026-06-24T19:00:00.000Z', null, null),
  (12, 'group', 'B', 'Bosnia & Herzegovina', 'Qatar', '2026-06-24T19:00:00.000Z', null, null),
  (13, 'group', 'C', 'Brazil', 'Morocco', '2026-06-13T22:00:00.000Z', null, null),
  (14, 'group', 'C', 'Haiti', 'Scotland', '2026-06-14T01:00:00.000Z', null, null),
  (15, 'group', 'C', 'Scotland', 'Morocco', '2026-06-19T22:00:00.000Z', null, null),
  (16, 'group', 'C', 'Brazil', 'Haiti', '2026-06-20T00:30:00.000Z', null, null),
  (17, 'group', 'C', 'Scotland', 'Brazil', '2026-06-24T22:00:00.000Z', null, null),
  (18, 'group', 'C', 'Morocco', 'Haiti', '2026-06-24T22:00:00.000Z', null, null),
  (19, 'group', 'D', 'USA', 'Paraguay', '2026-06-13T01:00:00.000Z', null, null),
  (20, 'group', 'D', 'Australia', 'Turkey', '2026-06-14T04:00:00.000Z', null, null),
  (21, 'group', 'D', 'USA', 'Australia', '2026-06-19T19:00:00.000Z', null, null),
  (22, 'group', 'D', 'Turkey', 'Paraguay', '2026-06-20T03:00:00.000Z', null, null),
  (23, 'group', 'D', 'Turkey', 'USA', '2026-06-26T02:00:00.000Z', null, null),
  (24, 'group', 'D', 'Paraguay', 'Australia', '2026-06-26T02:00:00.000Z', null, null),
  (25, 'group', 'E', 'Germany', 'Curaçao', '2026-06-14T17:00:00.000Z', null, null),
  (26, 'group', 'E', 'Ivory Coast', 'Ecuador', '2026-06-14T23:00:00.000Z', null, null),
  (27, 'group', 'E', 'Germany', 'Ivory Coast', '2026-06-20T20:00:00.000Z', null, null),
  (28, 'group', 'E', 'Ecuador', 'Curaçao', '2026-06-21T00:00:00.000Z', null, null),
  (29, 'group', 'E', 'Curaçao', 'Ivory Coast', '2026-06-25T20:00:00.000Z', null, null),
  (30, 'group', 'E', 'Ecuador', 'Germany', '2026-06-25T20:00:00.000Z', null, null),
  (31, 'group', 'F', 'Netherlands', 'Japan', '2026-06-14T20:00:00.000Z', null, null),
  (32, 'group', 'F', 'Sweden', 'Tunisia', '2026-06-15T02:00:00.000Z', null, null),
  (33, 'group', 'F', 'Netherlands', 'Sweden', '2026-06-20T17:00:00.000Z', null, null),
  (34, 'group', 'F', 'Tunisia', 'Japan', '2026-06-21T04:00:00.000Z', null, null),
  (35, 'group', 'F', 'Japan', 'Sweden', '2026-06-25T23:00:00.000Z', null, null),
  (36, 'group', 'F', 'Tunisia', 'Netherlands', '2026-06-25T23:00:00.000Z', null, null),
  (37, 'group', 'G', 'Belgium', 'Egypt', '2026-06-15T19:00:00.000Z', null, null),
  (38, 'group', 'G', 'Iran', 'New Zealand', '2026-06-16T01:00:00.000Z', null, null),
  (39, 'group', 'G', 'Belgium', 'Iran', '2026-06-21T19:00:00.000Z', null, null),
  (40, 'group', 'G', 'New Zealand', 'Egypt', '2026-06-22T01:00:00.000Z', null, null),
  (41, 'group', 'G', 'Egypt', 'Iran', '2026-06-27T03:00:00.000Z', null, null),
  (42, 'group', 'G', 'New Zealand', 'Belgium', '2026-06-27T03:00:00.000Z', null, null),
  (43, 'group', 'H', 'Spain', 'Cape Verde', '2026-06-15T16:00:00.000Z', null, null),
  (44, 'group', 'H', 'Saudi Arabia', 'Uruguay', '2026-06-15T22:00:00.000Z', null, null),
  (45, 'group', 'H', 'Spain', 'Saudi Arabia', '2026-06-21T16:00:00.000Z', null, null),
  (46, 'group', 'H', 'Uruguay', 'Cape Verde', '2026-06-21T22:00:00.000Z', null, null),
  (47, 'group', 'H', 'Cape Verde', 'Saudi Arabia', '2026-06-27T00:00:00.000Z', null, null),
  (48, 'group', 'H', 'Uruguay', 'Spain', '2026-06-27T00:00:00.000Z', null, null),
  (49, 'group', 'I', 'France', 'Senegal', '2026-06-16T19:00:00.000Z', null, null),
  (50, 'group', 'I', 'Iraq', 'Norway', '2026-06-16T22:00:00.000Z', null, null),
  (51, 'group', 'I', 'France', 'Iraq', '2026-06-22T21:00:00.000Z', null, null),
  (52, 'group', 'I', 'Norway', 'Senegal', '2026-06-23T00:00:00.000Z', null, null),
  (53, 'group', 'I', 'Norway', 'France', '2026-06-26T19:00:00.000Z', null, null),
  (54, 'group', 'I', 'Senegal', 'Iraq', '2026-06-26T19:00:00.000Z', null, null),
  (55, 'group', 'J', 'Argentina', 'Algeria', '2026-06-17T01:00:00.000Z', null, null),
  (56, 'group', 'J', 'Austria', 'Jordan', '2026-06-17T04:00:00.000Z', null, null),
  (57, 'group', 'J', 'Argentina', 'Austria', '2026-06-22T17:00:00.000Z', null, null),
  (58, 'group', 'J', 'Jordan', 'Algeria', '2026-06-23T03:00:00.000Z', null, null),
  (59, 'group', 'J', 'Algeria', 'Austria', '2026-06-28T02:00:00.000Z', null, null),
  (60, 'group', 'J', 'Jordan', 'Argentina', '2026-06-28T02:00:00.000Z', null, null),
  (61, 'group', 'K', 'Portugal', 'DR Congo', '2026-06-17T17:00:00.000Z', null, null),
  (62, 'group', 'K', 'Uzbekistan', 'Colombia', '2026-06-18T02:00:00.000Z', null, null),
  (63, 'group', 'K', 'Portugal', 'Uzbekistan', '2026-06-23T17:00:00.000Z', null, null),
  (64, 'group', 'K', 'Colombia', 'DR Congo', '2026-06-24T02:00:00.000Z', null, null),
  (65, 'group', 'K', 'Colombia', 'Portugal', '2026-06-27T23:30:00.000Z', null, null),
  (66, 'group', 'K', 'DR Congo', 'Uzbekistan', '2026-06-27T23:30:00.000Z', null, null),
  (67, 'group', 'L', 'England', 'Croatia', '2026-06-17T20:00:00.000Z', null, null),
  (68, 'group', 'L', 'Ghana', 'Panama', '2026-06-17T23:00:00.000Z', null, null),
  (69, 'group', 'L', 'England', 'Ghana', '2026-06-23T20:00:00.000Z', null, null),
  (70, 'group', 'L', 'Panama', 'Croatia', '2026-06-23T23:00:00.000Z', null, null),
  (71, 'group', 'L', 'Panama', 'England', '2026-06-27T21:00:00.000Z', null, null),
  (72, 'group', 'L', 'Croatia', 'Ghana', '2026-06-27T21:00:00.000Z', null, null),
  (73, 'R32', null, '2A', '2B', '2026-06-28T19:00:00.000Z', null, null),
  (74, 'R32', null, '1E', '3A/B/C/D/F', '2026-06-29T20:30:00.000Z', null, null),
  (75, 'R32', null, '1F', '2C', '2026-06-30T01:00:00.000Z', null, null),
  (76, 'R32', null, '1C', '2F', '2026-06-29T17:00:00.000Z', null, null),
  (77, 'R32', null, '1I', '3C/D/F/G/H', '2026-06-30T21:00:00.000Z', null, null),
  (78, 'R32', null, '2E', '2I', '2026-06-30T17:00:00.000Z', null, null),
  (79, 'R32', null, '1A', '3C/E/F/H/I', '2026-07-01T01:00:00.000Z', null, null),
  (80, 'R32', null, '1L', '3E/H/I/J/K', '2026-07-01T16:00:00.000Z', null, null),
  (81, 'R32', null, '1D', '3B/E/F/I/J', '2026-07-02T00:00:00.000Z', null, null),
  (82, 'R32', null, '1G', '3A/E/H/I/J', '2026-07-01T20:00:00.000Z', null, null),
  (83, 'R32', null, '2K', '2L', '2026-07-02T23:00:00.000Z', null, null),
  (84, 'R32', null, '1H', '2J', '2026-07-02T19:00:00.000Z', null, null),
  (85, 'R32', null, '1B', '3E/F/G/I/J', '2026-07-03T03:00:00.000Z', null, null),
  (86, 'R32', null, '1J', '2H', '2026-07-03T22:00:00.000Z', null, null),
  (87, 'R32', null, '1K', '3D/E/I/J/L', '2026-07-04T01:30:00.000Z', null, null),
  (88, 'R32', null, '2D', '2G', '2026-07-03T18:00:00.000Z', null, null),
  (89, 'R16', null, 'W74', 'W77', '2026-07-04T21:00:00.000Z', null, null),
  (90, 'R16', null, 'W73', 'W75', '2026-07-04T17:00:00.000Z', null, null),
  (91, 'R16', null, 'W76', 'W78', '2026-07-05T20:00:00.000Z', null, null),
  (92, 'R16', null, 'W79', 'W80', '2026-07-06T00:00:00.000Z', null, null),
  (93, 'R16', null, 'W83', 'W84', '2026-07-06T19:00:00.000Z', null, null),
  (94, 'R16', null, 'W81', 'W82', '2026-07-07T00:00:00.000Z', null, null),
  (95, 'R16', null, 'W86', 'W88', '2026-07-07T16:00:00.000Z', null, null),
  (96, 'R16', null, 'W85', 'W87', '2026-07-07T20:00:00.000Z', null, null),
  (97, 'QF', null, 'W89', 'W90', '2026-07-09T20:00:00.000Z', null, null),
  (98, 'QF', null, 'W93', 'W94', '2026-07-10T19:00:00.000Z', null, null),
  (99, 'QF', null, 'W91', 'W92', '2026-07-11T21:00:00.000Z', null, null),
  (100, 'QF', null, 'W95', 'W96', '2026-07-12T01:00:00.000Z', null, null),
  (101, 'SF', null, 'W97', 'W98', '2026-07-14T19:00:00.000Z', null, null),
  (102, 'SF', null, 'W99', 'W100', '2026-07-15T19:00:00.000Z', null, null),
  (103, '3rd', null, 'L101', 'L102', '2026-07-18T21:00:00.000Z', null, null),
  (104, 'Final', null, 'W101', 'W102', '2026-07-19T19:00:00.000Z', null, null)
on conflict (match_no) do update set
  stage       = excluded.stage,
  group_label = excluded.group_label,
  home_team   = excluded.home_team,
  away_team   = excluded.away_team,
  kickoff     = excluded.kickoff,
  home_score  = coalesce(excluded.home_score, matches.home_score),
  away_score  = coalesce(excluded.away_score, matches.away_score);
