// Generates schema.sql from the openfootball 2026 feed.
//   node scripts/gen-schema.mjs            # fetches the live feed
//   node scripts/gen-schema.mjs <file>     # uses a local JSON file
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseFixtures, OPENFOOTBALL_2026_URL } from '../lib/parseFixtures.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

function sqlStr(v) {
  if (v === null || v === undefined) return 'null';
  return `'${String(v).replace(/'/g, "''")}'`;
}
function sqlNum(v) {
  return v === null || v === undefined ? 'null' : String(v);
}

const data = process.argv[2]
  ? JSON.parse(readFileSync(process.argv[2], 'utf8'))
  : await fetch(OPENFOOTBALL_2026_URL).then((r) => r.json());

const matches = parseFixtures(data);

const rows = matches
  .map(
    (m) =>
      `  (${m.match_no}, ${sqlStr(m.stage)}, ${sqlStr(m.group_label)}, ${sqlStr(
        m.home_team,
      )}, ${sqlStr(m.away_team)}, ${sqlStr(m.kickoff)}, ${sqlNum(
        m.home_score,
      )}, ${sqlNum(m.away_score)})`,
  )
  .join(',\n');

const sql = `-- Family World Cup 2026 — Supabase schema + seed (generated by scripts/gen-schema.mjs)
-- HOW TO USE: open your Supabase project → SQL Editor → paste this whole file → Run.
-- Safe to re-run: it creates tables only if missing and upserts the fixtures.

-- ---------- tables ----------
create table if not exists players (
  id         bigint generated always as identity primary key,
  name       text not null,
  sort_order int  not null default 0
);

create table if not exists matches (
  match_no    int  primary key,
  stage       text not null,            -- group | R32 | R16 | QF | SF | 3rd | Final
  group_label text,                     -- A..L for the group stage, null otherwise
  home_team   text not null,
  away_team   text not null,
  kickoff     timestamptz not null,     -- stored in UTC, shown in each viewer's local time
  home_score  int,                      -- null until the match is played / synced
  away_score  int
);

create table if not exists predictions (
  id         bigint generated always as identity primary key,
  match_no   int    not null references matches(match_no) on delete cascade,
  player_id  bigint not null references players(id) on delete cascade,
  pred_home  int    not null check (pred_home >= 0 and pred_home <= 99),
  pred_away  int    not null check (pred_away >= 0 and pred_away <= 99),
  updated_at timestamptz not null default now(),
  unique (match_no, player_id)
);

-- ---------- row level security (trust-based, no login) ----------
alter table players     enable row level security;
alter table matches     enable row level security;
alter table predictions enable row level security;

drop policy if exists "read players"        on players;
drop policy if exists "rename players"       on players;
drop policy if exists "add players"          on players;
drop policy if exists "remove players"       on players;
drop policy if exists "read matches"         on matches;
drop policy if exists "read predictions"     on predictions;
drop policy if exists "insert predictions"   on predictions;
drop policy if exists "update predictions"   on predictions;

-- everyone can read everything
create policy "read players"     on players     for select using (true);
create policy "read matches"     on matches     for select using (true);
create policy "read predictions" on predictions for select using (true);

-- anyone can rename / add / remove players (Settings screen) — trust-based
create policy "rename players" on players for update using (true) with check (true);
create policy "add players"    on players for insert with check (true);
create policy "remove players" on players for delete using (true);

-- predictions can be written/edited only BEFORE kickoff (authoritative lock)
create policy "insert predictions" on predictions for insert
  with check (exists (
    select 1 from matches m where m.match_no = predictions.match_no and now() < m.kickoff
  ));
create policy "update predictions" on predictions for update
  using (exists (
    select 1 from matches m where m.match_no = predictions.match_no and now() < m.kickoff
  ))
  with check (exists (
    select 1 from matches m where m.match_no = predictions.match_no and now() < m.kickoff
  ));
-- NOTE: 'matches' has no anon write policy, so scores/fixtures can only be changed
-- by the daily sync function, which uses the service-role key and bypasses RLS.

-- ---------- seed: 5 players (only if the table is empty) ----------
insert into players (name, sort_order)
select v.name, v.sort_order
from (values
  ('Player 1', 1), ('Player 2', 2), ('Player 3', 3), ('Player 4', 4), ('Player 5', 5)
) as v(name, sort_order)
where not exists (select 1 from players);

-- ---------- seed: 104 fixtures ----------
insert into matches (match_no, stage, group_label, home_team, away_team, kickoff, home_score, away_score) values
${rows}
on conflict (match_no) do update set
  stage       = excluded.stage,
  group_label = excluded.group_label,
  home_team   = excluded.home_team,
  away_team   = excluded.away_team,
  kickoff     = excluded.kickoff,
  home_score  = coalesce(excluded.home_score, matches.home_score),
  away_score  = coalesce(excluded.away_score, matches.away_score);
`;

writeFileSync(join(root, 'schema.sql'), sql);
console.log(`Wrote schema.sql with ${matches.length} fixtures.`);
